### ISSUE TITLE
socket.error: [Errno 111] Connection refused  Please Help ?

### ISSUE THREAD

**Issue by muratoznn** [Synacktiv-contrib/Modmobjam#3]
python '/root/Downloads/ngrok-stable-linux-amd64zz/Modmobjam-master/smartjam_rpcclient.py' -f '/root/Downloads/ngrok-stable-linux-amd64zz/Modmobjam-master/cells_1572015304.json'
[+] Jamming cell 0x8ed2c4-9788 central frequency at 1957.6 MHz with 10 MHz bandwidth
Traceback (most recent call last):
  File "/root/Downloads/ngrok-stable-linux-amd64zz/Modmobjam-master/smartjam_rpcclient.py", line 100, in <module>
    s.set_var_cent_freq(val['freq']*1000000)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1065, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 892, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 854, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 831, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

**Comment by muratoznn** [comment]
please Help ?

**Comment by FlUxIuS** [comment]
Does the jamming service is run before launching the client "smartjam_rpcclient.py"?
